puts "The students of Twin Peaks Academy"
puts "--------------"
puts "Laura Palmer"
puts "Bobby Briggs"
puts "Dr Lawrence Jacoby"
puts "One-eyed Jack"
puts "Dale Cooper"
puts "Sherriff Harry S Truman"
puts "Leland Palmer"
puts "Audrey Horne"
puts "Shelly Johnson"
puts "Log Lady"
puts "Nadine Hurley"
